### PR TITLE
[build] support scala 2.12 and a cross compilation for 2.11, 2.12

### PR DESCRIPTION
**Pull request by regis-leray**

### CODE REVIEW

**Comment by regis-leray** [comment]
@kypeli i dont really understand what are you asking. i created the branch on my fork, and created a Pull Request... You can now do Rebase and Merge, if you dont want a extra commit.

Also i dont have the write access on the repo, only you at this time, i try to push on `	git@github.com:kypeli/sversion.git ` didnt work as you can see 

```
ERROR: Permission to kypeli/sversion.git denied to regis-leray.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by kypeli** [comment]
You can do a pull request against the original repository that you forked from. That's what I was basically asking for.

**Comment by regis-leray** [comment]
Hummm not sure
the pull request is targeting already the original repository on the `master` branch
```git@github.com:kypeli/sversion.git```

**Comment by regis-leray** [comment]
look the pull request ```	regis-leray  wants to merge 1 commit into kypeli:master from regis-leray:cross-versions ```

**Comment by kypeli** [comment]
Thank you :+1:

**Pull request merged**
