### PR TITLE
logger - remove logback from the resources, should never provide this configuration for a library

### PR DESCRIPTION
**Pull request by regis-leray**
Currently you include a logback configuration in your library, and it is not a good pratice.
Logback will detect multiple configuration, and will pickup on from the classpath

log example

```
2:50:09,412 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
12:50:09,412 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/opt/XXX-sync/lib/XXX-sync-0.5.2-SNAPSHOT.jar!/logback.xml]
12:50:09,412 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/opt/omrun-sync/lib/com.github.kypeli.sversion_2.11-1.0.jar!/logback.xml]
```

### CODE REVIEW

**Comment by kypeli** [comment]
Thanks a lot for the contribution! It's my first Scala library, so have to keep on learning.

**Comment by regis-leray** [comment]
could you please release a new version. thanks

**Comment by kypeli** [comment]
I can do a new release later today local time. Will update this thread once it's done.

**Comment by kypeli** [comment]
I just released version 1.1.1 to Sonatype repositories. Hopefully it'll be available shortly.

**Comment by regis-leray** [comment]
Thanks

**Pull request merged**
